@startuml diagramma
actor "Пользователь" as U
boundary "Интерфейс" as UI
control "Сервер" as S
participant "Классификатор сущностей" as WIT
participant "API" as VK
participant "Документ" as KB
participant "LLM" as LLM

U -> UI: Отправка запроса
UI -> S: Передача запроса на сервер
S -> WIT: Определение метода обработки
WIT --> S: ID функции

alt Если требуется доступ к социальной сети
    S -> VK: Запрос данных из API
    VK --> S: Полученные данные
else Если вопрос общий
    S -> KB: Поиск релевантных чанков
    KB --> S: Полученные данные
end

S -> LLM: Формирование промпта
LLM --> S: Сгенерированный ответ
S --> UI: Передача ответа пользователю
UI --> U: Отображение ответа
@enduml
